import Head from "next/head";
import Layout from "../components/Layout";
import Button from "@mui/material/Button";
import AccessAlarmIcon from "@mui/icons-material/AccessAlarm";
import BookmarkBorderIcon from "@mui/icons-material/BookmarkBorder";
import { ButtonGroup } from "@mui/material";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ButtonGroup variant="outlined">
        <Button color="secondary" startIcon={<AccessAlarmIcon />}>
          Alarm
        </Button>
        <Button color="success" startIcon={<BookmarkBorderIcon />}>
          Save
        </Button>
      </ButtonGroup>
      <h2>Home page</h2>
    </Layout>
  );
}
